apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.commonApi.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.commonApi.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.commonApi.port }}
      targetPort: {{ .Values.commonApi.port }}