apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  labels:
    app: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image }}:{{ .Values.ui.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.port }}
          env:
            - name: APP_ENVIRONMENT
              value: {{ .Values.ui.env }}